"""add header row range to sheet_relationships

Revision ID: fd27237322e0
Revises: bf9ae7957e64
Create Date: 2026-09-17 13:29:51.110813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd27237322e0'
down_revision: Union[str, Sequence[str], None] = 'bf9ae7957e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default='1' backfills any existing row (the old code always assumed a single
    # header row at row 1) without touching data — dropped right after so it doesn't linger
    # as an implicit default for future inserts, which should always specify this explicitly.
    op.add_column(
        'sheet_relationships',
        sa.Column('header_start_row', sa.Integer(), nullable=False, server_default='1'),
    )
    op.add_column(
        'sheet_relationships',
        sa.Column('header_end_row', sa.Integer(), nullable=False, server_default='1'),
    )
    op.alter_column('sheet_relationships', 'header_start_row', server_default=None)
    op.alter_column('sheet_relationships', 'header_end_row', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sheet_relationships', 'header_end_row')
    op.drop_column('sheet_relationships', 'header_start_row')
    # ### end Alembic commands ###
