"""create initial tables

Revision ID: bf9ae7957e64
Revises: 
Create Date: 2026-09-01 09:34:22.795421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf9ae7957e64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workbooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workbooks_owner_id'), 'workbooks', ['owner_id'], unique=False)
    op.create_table('worksheets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workbook_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sheet_type', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('content_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worksheets_workbook_id'), 'worksheets', ['workbook_id'], unique=False)
    op.create_table('conversions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worksheet_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worksheet_id'], ['worksheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversions_worksheet_id'), 'conversions', ['worksheet_id'], unique=False)
    op.create_table('sheet_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_worksheet_id', sa.UUID(), nullable=False),
    sa.Column('child_worksheet_id', sa.UUID(), nullable=False),
    sa.Column('selected_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filter_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('parent_worksheet_id != child_worksheet_id', name='ck_parent_ne_child'),
    sa.ForeignKeyConstraint(['child_worksheet_id'], ['worksheets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_worksheet_id'], ['worksheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sheet_relationships_child_worksheet_id'), 'sheet_relationships', ['child_worksheet_id'], unique=True)
    op.create_index(op.f('ix_sheet_relationships_parent_worksheet_id'), 'sheet_relationships', ['parent_worksheet_id'], unique=False)
    op.create_table('word_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversion_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversion_id'], ['conversions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_documents_conversion_id'), 'word_documents', ['conversion_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_documents_conversion_id'), table_name='word_documents')
    op.drop_table('word_documents')
    op.drop_index(op.f('ix_sheet_relationships_parent_worksheet_id'), table_name='sheet_relationships')
    op.drop_index(op.f('ix_sheet_relationships_child_worksheet_id'), table_name='sheet_relationships')
    op.drop_table('sheet_relationships')
    op.drop_index(op.f('ix_conversions_worksheet_id'), table_name='conversions')
    op.drop_table('conversions')
    op.drop_index(op.f('ix_worksheets_workbook_id'), table_name='worksheets')
    op.drop_table('worksheets')
    op.drop_index(op.f('ix_workbooks_owner_id'), table_name='workbooks')
    op.drop_table('workbooks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
